# **Numpy**
NumPy is a library in python used for working with arrays

In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5,6]

In [3]:
arr = np.array(my_lst)

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(6,)

In [7]:
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[11,12,13,14,15]

In [8]:
arr1=np.array([my_list1,my_list2,my_list3])

In [9]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
arr1.shape

(3, 5)

In [11]:
arr1.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [12]:
arr1.shape

(3, 5)

In [13]:
arr1.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [14]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
arr1[1][2]

8

In [19]:
arr1[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15]])

In [20]:
arr1[:, 1:]   # : means all the rows, 1: means starting from col index 1

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [21]:
arr1[:2, :2]  #  upto 2 index row and colmn wise

array([[1, 2],
       [6, 7]])

In [22]:
arr= np.arange(0,10)    # arange between 0 to 10 all the elements will be printed

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr= np.arange(0,10, step=2) 

In [25]:
arr

array([0, 2, 4, 6, 8])

In [26]:
np.linspace(1, 10, 50)      # Prints equally spaced numbers between 1 to 10 

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [33]:
## Copy() function and  broadcasting
arr2 =arr
arr2

array([0, 2, 4, 6, 8])

In [34]:
arr2[3:]=100    # broadcasting
arr2

array([  0,   2,   4, 100, 100])

In [35]:
arr   # Refernce type. The original copy of arr is also updated

array([  0,   2,   4, 100, 100])

In order to prevent this problem we will use a copy of  the array

In [36]:
arr1=arr.copy()


In [37]:
print(arr)

[  0   2   4 100 100]


In [38]:
arr1[3:]=500
arr1

array([  0,   2,   4, 500, 500])

In [39]:
arr                 #  arr is not changed when we use a copy of arr

array([  0,   2,   4, 100, 100])

In [41]:
# Some conditions useful in Exploratory data analysis

val = 2
arr < 2    # Whichever element is <2 gives the O/P true

array([ True, False, False, False, False])

In [43]:
arr*3   # all the elements gets multiplied with  3  

array([  0,   6,  12, 300, 300])

In [45]:
arr[arr<10]

array([0, 2, 4])

In [46]:
## Create array and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [48]:
# Creating arrray consisting of ones

np.ones(4)

array([1., 1., 1., 1.])

In [49]:
np.ones((5,2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

####Random Distribution

In [51]:
np.random.rand(4,4)   # Creates array of random numbers in 4x4 array

array([[0.92436709, 0.39715458, 0.81144517, 0.69103132],
       [0.73520842, 0.21678441, 0.98286166, 0.51226292],
       [0.38821088, 0.19409432, 0.28253682, 0.5155443 ],
       [0.35095388, 0.17648796, 0.00854799, 0.17949384]])

In [53]:
np.random.randn(4,4)   # Creates an array of  random numbers using standard normal distribution

array([[-0.80686892, -2.66323805,  1.65741365,  0.7141555 ],
       [ 1.03132602, -0.26188813,  1.50435423,  0.28973457],
       [-0.74298937,  0.53207979,  1.06116699, -1.61459617],
       [ 1.84090338, -0.51856017,  0.61733745,  1.37035207]])

In [56]:
np.random.randint(0,100,10).reshape(2,5)

array([[57, 92, 97,  4, 56],
       [11, 68, 50, 98,  4]])

In [62]:
np.random.random_sample((5,10))

array([[0.0994198 , 0.21073273, 0.87962592, 0.8232943 , 0.09848483,
        0.68978766, 0.32443819, 0.30013114, 0.97513962, 0.66550135],
       [0.96765379, 0.5241836 , 0.58690306, 0.41468296, 0.31708304,
        0.18920061, 0.45932249, 0.19048481, 0.84696399, 0.79184734],
       [0.20941437, 0.95710942, 0.29415238, 0.2825285 , 0.66068091,
        0.83017891, 0.405699  , 0.23413865, 0.19067967, 0.28158348],
       [0.86599108, 0.06975598, 0.92931489, 0.68271389, 0.57851188,
        0.78143747, 0.53592072, 0.41220336, 0.53976312, 0.67396474],
       [0.07653046, 0.70176042, 0.29899558, 0.99629062, 0.65471526,
        0.51244732, 0.92365326, 0.57569116, 0.59084133, 0.51323375]])